
export const  CREATE_POST_START = "CREATE_POST_START";
export const  CREATE_POST_FAIL = "CREATE_POST_FAIL"
export const  CREATE_POST_SUCCESS = "CREATE_POST_SUCCESS"

export const  EDIT_PROFILE_START = "EDIT_PROFILE_START"
export const  EDIT_PROFILE_SUCCESS = "EDIT_PROFILE_SUCCESS"
export const  EDIT_PROFILE_FAIL = "EDIT_PROFILE_FAIL"

export const  GET_TIMELINE_POST_START = "GET_TIMELINE_POST_START"
export const  GET_TIMELINE_POST_SUCCESS = "GET_TIMELINE_POST_SUCCESS"
export const  GET_TIMELINE_POST_FAIL = "GET_TIMELINE_POST_FAIL"

export const  GET_HOME_POST_START = "GET_HOME_POST_START"
export const  GET_HOME_POST_SUCCESS = "GET_HOME_POST_SUCCESS"
export const  GET_HOME_POST_FAIL = "GET_HOME_POST_FAIL"